runtime: python39
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  UNSPLASH_ACCESS_KEY: YEd_cGH_N_X1WqVAnbLw9E3ET2g9KM3BHX0fWlKYTII

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

inbound_services:
- warmup 